
services:
  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_name
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network 

  fastapi:
    build: .
    ports:
      - 80:8000
    networks:
      - my_network
    restart: on-failure

networks:
  my_network: 

volumes:
  db_data:
