version: "3.9"
services:
  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_name
    volumes:
      - db_data:/var/lib/postgresql/data
      #- ./init.db/:/docker-entrypoint-initdb.d/
    networks:
      - my_network 
    ports:
      - "5432:5432"


  fastapi:
    build: .
    
    # volumes:
    #   - ./:/app
    depends_on:
      - db
    ports:
      - 80:8000
    networks:
      - my_network
    command: uvicorn library_service.main:app --host 0.0.0.0 --port 8000
networks:
  my_network: 

volumes:
  db_data:
